version: 2
updates:
  # 🛡️ Blindaje de GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" 
    schedule:
      interval: "weekly" # Auditoría más frecuente para detectar parches de seguridad rápido
    # Impedir actualizaciones automáticas de versiones mayores que puedan romper el Nodo
    versioning-strategy: "lockfile-only" 
    open-pull-requests-limit: 3

  # 🛡️ Blindaje de Bundler (Ruby)
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    # Solo permitir actualizaciones de seguridad
    allow:
      - dependency-type: "production"
    versioning-strategy: "increase-if-necessary"
